import pytest
from lib.vsr1000 import *

'''

def test_failed_auth():
    with pytest.raises(Exception) as e:
        router = VSR1000("127.0.0.1", 830, "test", "test")
        config = '<></>'
        router.get_config(config)
    assert str(e.value) == "auth erro"

def test_list_loopback():
    router = VSR1000("127.0.0.1", 830, "test", "test")
    config = '<></>'
    result = router.get_config(config)
    assert True

def test_add_loopback():
    router = VSR1000("127.0.0.1", 830, "test", "test")
    config = '<></>'
    result = router.get_config(config)
    assert True

def test_del_loopback():
    router = VSR1000("127.0.0.1", 830, "test", "test")
    config = '<></>'
    result = router.get_config(config)
    assert True

'''